var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);
function d(a,b){if(b)a:{var c=ca;a=a.split(".");for(var g=0;g<a.length-1;g++){var k=a[g];if(!(k in c))break a;c=c[k]}a=a[a.length-1];g=c[a];b=b(g);b!=g&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}d("Array.prototype.fill",function(a){return a?a:function(b,c,g){var k=this.length||0;0>c&&(c=Math.max(0,k+c));if(null==g||g>k)g=k;g=Number(g);0>g&&(g=Math.max(0,k+g));for(c=Number(c||0);c<g;c++)this[c]=b;return this}});function e(a){return a?a:Array.prototype.fill}
d("Int8Array.prototype.fill",e);d("Uint8Array.prototype.fill",e);d("Uint8ClampedArray.prototype.fill",e);d("Int16Array.prototype.fill",e);d("Uint16Array.prototype.fill",e);d("Int32Array.prototype.fill",e);d("Uint32Array.prototype.fill",e);d("Float32Array.prototype.fill",e);d("Float64Array.prototype.fill",e);window.kaRun=da;window.kaFormat=ea;window.kaStop=f;window.easykey=fa;window.easyrun=h;window.easygo=ha;window.easyinit=l;window.easyinp=ia;var m=[],n=0,p=null,q=null,r=null,t;
function u(a){if(p=a)p.c=!1,300==p.width&&150==p.height&&(p.width=600,p.height=600)}function ha(a,b,c){b=void 0===b?null:b;c=void 0===c?null:c;u(b);b&&v();if(q=c)q.value="";t=!0;w.postMessage(["run",a,2,-1,null])}function h(a,b,c){m.push([a,void 0===b?null:b,void 0===c?null:c]);0==n&&l(m[0][1]);2>n||(p&&p.c?f():x())}function x(){if(!t&&0!=m.length){var a=null,b=m.shift();1<b.length&&u(b[1]);2<b.length&&(a=b[2]);v();t=!0;w.postMessage(["runx",b[0],0,-1,a])}}
function z(a,b){r&&r(a,void 0===b?null:b)}function v(){A();B=p.getContext("2d");C(8);B.lineWidth=6;D(3);B.a=0;B.b=0;E=null}var F=!1;function da(a,b,c,g){b=void 0===b?null:b;c=void 0===c?0:c;g=void 0===g?-1:g;(p=G)&&v();F=!1;255<c&&(H=null,F=!0);t=!1;w.postMessage(["run",a,c,g,b])}function ea(a,b){b=void 0===b?null:b;null==b?w.postMessage(["format",a]):w&&w.postMessage(["formatID",a,b])}function f(){I();p&&p.c?(w.postMessage(["stop_ping"]),A(),J=setTimeout(ja,500)):(w.terminate(),K())}
var B=null,L=null,M=null;function A(){p.c&&(p.c=!1,p.onmouseout=null,p.onmousedown=null,p.onmouseup=null,p.onmousemove=null,p.ontouchmove=null,p.ontouchstart=null,p.ontouchend=null,p.removeEventListener("keydown",N),p.removeAttribute("tabIndex"),L&&(cancelAnimationFrame(L),L=null),M&&(clearTimeout(M),M=null),p.style.cursor="default")}function O(a,b){var c=B.lineWidth/2;B.beginPath();B.arc(a,b,c,0,2*Math.PI);B.fill()}function C(a){B.font=""+Math.round(6*a)+"px monospace";B.h=5*a}
function D(a){1==a?E?B.putImageData(E,0,0):B.clearRect(0,0,600,600):2==a?E=B.getImageData(0,0,600,600):3==a?(a=window.getComputedStyle(p,null).color,B.fillStyle=a,B.strokeStyle=a):4==a?(a=window.getComputedStyle(p,null).backgroundColor,B.fillStyle=a,B.strokeStyle=a):10==a&&(a=p.toDataURL().substr(22),P(a+"\n"))}var H,E;
function Q(a){switch(a[0]){case 1:B.a=6*a[1];B.b=6*a[2];break;case 2:var b=a[1];a=a[2];b*=6;a*=6;B.beginPath();B.moveTo(B.a,B.b);B.lineTo(b,a);B.stroke();O(B.a,B.b);O(b,a);B.a=b;B.b=a;break;case 3:B.beginPath();B.arc(B.a,B.b,6*a[1],0,2*Math.PI);B.fill();break;case 4:B.fillRect(B.a,B.b,6*a[1],6*a[2]);break;case 5:b=a[1];if(!(2>b.length)){B.beginPath();B.moveTo(6*b[0][0],6*b[0][1]);for(a=1;a<b.length;a++)B.lineTo(6*b[a][0],6*b[a][1]);B.fill()}break;case 6:B.fillText(a[1],B.a,B.b+B.h);break;case 7:D(a[1]);
break;case 8:B.lineWidth=6*a[1];break;case 9:b="rgb("+a[1]+","+a[2]+","+a[3]+")";B.fillStyle=b;B.strokeStyle=b;break;case 10:C(a[1]);break;case 11:p.c&&a[1]<R.length&&(p.style.cursor=R[a[1]]);break;case 12:if(b=a[1],!(2>b.length)){a=6*b[0][0];var c=6*b[0][1];O(a,c);B.beginPath();B.moveTo(a,c);if(2==b.length){var g=6*b[1][0],k=6*b[1][1];B.lineTo(a,c)}else{for(var y=1;;){a=6*b[y][0];c=6*b[y][1];g=6*b[y+1][0];k=6*b[y+1][1];if(y==b.length-2)break;B.quadraticCurveTo(a,c,(a+g)/2,(c+k)/2);y+=1}B.quadraticCurveTo(a,
c,g,k)}B.stroke();O(g,k)}}}var R=["default","crosshair","pointer"];function ka(a){if(1==a.length)a=a[0],F&&7>=a[0]&&H&&B.putImageData(H,B.a-6,B.b-6),Q(a),F&&7>=a[0]&&(H=B.getImageData(B.a-6,B.b-6,12,12),a=B.fillStyle,B.fillStyle="red",B.beginPath(),B.arc(B.a,B.b,6,0,2*Math.PI),B.fill(),B.fillStyle=a);else for(var b=0;b<a.length;b++)Q(a[b])}function ja(){w.terminate();K()}var J,S=null,T;function I(){S&&(S.close(),S.f&&clearTimeout(S.f),S=null)}
function la(){var a=T.shift(),b=1E3*a[1];S.g.frequency.setValueAtTime(a[0],S.currentTime);S.gain.gain.setTargetAtTime(1,S.currentTime,.01);S.f=setTimeout(ma,b)}function ma(){S.gain.gain.setTargetAtTime(0,S.currentTime,.05);0!=T.length&&(S.f=setTimeout(la,150))}function na(){S=new (window.AudioContext||window.webkitAudioContext);S.g=S.createOscillator();S.gain=S.createGain();S.gain.gain.setValueAtTime(0,S.currentTime);S.g.connect(S.gain);S.gain.connect(S.destination);S.g.start()}
function oa(a){S||na();S.f&&(clearTimeout(S.f),S.gain.gain.setTargetAtTime(0,S.currentTime,.05));T=a;0!=T.length&&la()}var U=!1;function pa(a){var b=p.getBoundingClientRect();U=!0;var c=p.width/b.width/6;w.postMessage(["mouse",0,(a.clientX-b.left)*c,(a.clientY-b.top)*c]);p.focus();a.preventDefault()}function qa(a){V=a.touches[0];a.clientX=V.clientX;a.clientY=V.clientY;pa(a)}
function W(a){var b=p.getBoundingClientRect();U=!1;var c=p.width/b.width/6;w.postMessage(["mouse",1,(a.clientX-b.left)*c,(a.clientY-b.top)*c]);a.preventDefault()}function ra(a){var b=p.getBoundingClientRect(),c=p.width/b.width/6;w.postMessage(["mouse",2,(a.clientX-b.left)*c,(a.clientY-b.top)*c]);a.preventDefault()}function P(a){if(q){var b=q.value;6E4<b.length&&(b=b.substr(1E3));q.value=b+a;q.scrollTop=q.scrollHeight}else console.log(a)}
function X(){S?(S.resume(),"running"==S.state&&(p.removeEventListener("mousedown",X),p.removeEventListener("touchstart",X),p.removeEventListener("touchend",X))):na()}var V;
function sa(a){a=a.data;switch(a[0]){case "list":ka(a[1]);break;case "print":P(a[1]);break;case "ide":a.shift();var b=a.shift();z(b,a);break;case "stderr":console.log(a[1]);break;case "started":console.log("started");window.sab=null;"function"==typeof SharedArrayBuffer&&(window.sab=new SharedArrayBuffer(112));w.postMessage(["init",window.sab,navigator.language.substring(0,2)]);1==n&&Y(null);n=2;t=!1;x();z("ready");break;case "done":F&&H&&B.putImageData(H,B.a-6,B.b-6);t=!1;x();z("stopped");p&&p.c&&
v();break;case "stop_pong":v();clearTimeout(J);t=!1;x();z("stopped");break;case "sound":oa(a[1]);break;case "timer":p.c&&ta(a[1]);break;case "init":if(0==(a[1]&32))break;if(!p){console.log("no canvas");w.terminate();z("info",[0]);K();break}z("canvon");p.c=!0;a[1]&15&&(p.focus(),a[1]&1&&(p.onmousedown=pa,p.ontouchstart=qa),a[1]&2&&(p.onmouseup=W,p.ontouchend=function(c){c.clientX=V.clientX;c.clientY=V.clientY;W(c)},p.onmouseout=function(c){U&&(c.clientX=0,c.clientY=0,W(c))},0==(a[1]&4)&&(p.ontouchmove=
function(c){V=c.touches[0]})),a[1]&4&&(p.onmousemove=ra,p.ontouchmove=function(c){V=c.touches[0];c.clientX=V.clientX;c.clientY=V.clientY;ra(c)}),a[1]&8&&(p.addEventListener("keydown",N,!1),p.tabIndex=0));a[1]&16&&(L||(L=requestAnimationFrame(ua)));a[1]&64&&(p.addEventListener("mousedown",X),p.addEventListener("touchstart",X),p.addEventListener("touchend",X));break;case "exit":A();I();w.terminate();z("info",[0]);K();break;case "error":t=!1;z("error");break;default:console.log("unknown command: "+a)}}
function K(){w=new Worker("easyw.js");w.onmessage=sa}function va(){w.postMessage(["timer"])}function ta(a){M&&(clearTimeout(M),M=null);0<=a&&(M=setTimeout(va,1E3*a))}function ua(){w.postMessage(["animate"]);L=requestAnimationFrame(ua)}function N(a){w.postMessage(["key",a.key]);a.preventDefault()}var w=null,G=null;function Y(a){q?a?P(a+"\n"):q.value="":p&&(a?(v(),B.fillText(a,60,60)):B&&D(1))}
function l(a,b,c){q=void 0===b?null:b;r=void 0===c?null:c;G=a;u(a);"object"!=typeof WebAssembly?(Y("no wasm support"),z("nowasm")):(K(),setTimeout(function(){1==n&&Y("Loading ...")},1E3));n=1}function fa(a){w.postMessage(["key",a])}function ia(a){var b=new Uint16Array(window.sab);if(a){b[4]=a.length+1;for(var c=0;c<a.length;c++)b[c+5]=a.charCodeAt(c)}else b[4]=0;b=new Int32Array(window.sab);Atomics.store(b,1,1);Atomics.notify?Atomics.notify(b,1,1):Atomics.wake(b,1,1)}
if(window.easyscript){var Z=window.easycanv;Z||(Z=document.querySelector("canvas"));h(window.easyscript,Z)};
