var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";
var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))return;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var f=a.split(".");a=1===f.length;d=f[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var k=0;k<f.length-1;k++){var g=f[k];if(!(g in d))return;d=d[g]}f=f[f.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[f]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+f,f=
$jscomp.propertyToPolyfillSymbol[f],$jscomp.defineProperty(d,f,{configurable:!0,writable:!0,value:b})))};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(g){return g instanceof f?g:new f(function(h,m){h(g)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(g){if(null==this.batch_){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(g)};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(g){d(g,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var g=
this.batch_;this.batch_=[];for(var h=0;h<g.length;++h){var m=g[h];g[h]=null;try{m()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(g){this.asyncExecuteFunction(function(){throw g;})};var f=function(g){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var h=this.createResolveAndReject_();try{g(h.resolve,h.reject)}catch(m){h.reject(m)}};f.prototype.createResolveAndReject_=function(){function g(l){return function(q){m||(m=!0,l.call(h,q))}}var h=this,m=!1;
return{resolve:g(this.resolveTo_),reject:g(this.reject_)}};f.prototype.resolveTo_=function(g){if(g===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof f)this.settleSameAsPromise_(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(g):this.fulfill_(g)}};f.prototype.resolveToNonPromiseObj_=function(g){var h=void 0;try{h=g.then}catch(m){this.reject_(m);return}"function"==typeof h?
this.settleSameAsThenable_(h,g):this.fulfill_(g)};f.prototype.reject_=function(g){this.settle_(2,g)};f.prototype.fulfill_=function(g){this.settle_(1,g)};f.prototype.settle_=function(g,h){if(0!=this.state_)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.state_);this.state_=g;this.result_=h;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var g=0;g<this.onSettledCallbacks_.length;++g)k.asyncExecute(this.onSettledCallbacks_[g]);
this.onSettledCallbacks_=null}};var k=new b;f.prototype.settleSameAsPromise_=function(g){var h=this.createResolveAndReject_();g.callWhenSettled_(h.resolve,h.reject)};f.prototype.settleSameAsThenable_=function(g,h){var m=this.createResolveAndReject_();try{g.call(h,m.resolve,m.reject)}catch(l){m.reject(l)}};f.prototype.then=function(g,h){function m(r,e){return"function"==typeof r?function(n){try{l(r(n))}catch(p){q(p)}}:e}var l,q,t=new f(function(r,e){l=r;q=e});this.callWhenSettled_(m(g,l),m(h,q));return t};
f.prototype.catch=function(g){return this.then(void 0,g)};f.prototype.callWhenSettled_=function(g,h){function m(){switch(l.state_){case 1:g(l.result_);break;case 2:h(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?k.asyncExecute(m):this.onSettledCallbacks_.push(m)};f.resolve=c;f.reject=function(g){return new f(function(h,m){m(g)})};f.race=function(g){return new f(function(h,m){for(var l=$jscomp.makeIterator(g),q=l.next();!q.done;q=l.next())c(q.value).callWhenSettled_(h,
m)})};f.all=function(g){var h=$jscomp.makeIterator(g),m=h.next();return m.done?c([]):new f(function(l,q){function t(n){return function(p){r[n]=p;e--;0==e&&l(r)}}var r=[],e=0;do r.push(void 0),e++,c(m.value).callWhenSettled_(t(r.length-1),q),m=h.next();while(!m.done)})};return f},"es6","es3");
$jscomp.polyfill("Array.prototype.copyWithin",function(a){function b(c){c=Number(c);return Infinity===c||-Infinity===c?c:c|0}return a?a:function(c,d,f){var k=this.length;c=b(c);d=b(d);f=void 0===f?k:b(f);c=0>c?Math.max(k+c,0):Math.min(c,k);d=0>d?Math.max(k+d,0):Math.min(d,k);f=0>f?Math.max(k+f,0):Math.min(f,k);if(c<d)for(;d<f;)d in this?this[c++]=this[d++]:(delete this[c++],d++);else for(f=Math.min(f,k+d-c),c+=f-d;f>d;)--f in this?this[--c]=this[f]:delete this[--c];return this}},"es6","es3");
$jscomp.typedArrayCopyWithin=function(a){return a?a:Array.prototype.copyWithin};$jscomp.polyfill("Int8Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint8ClampedArray.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Int16Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");
$jscomp.polyfill("Uint16Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Int32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Float32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Float64Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");
var Module="undefined"!==typeof Module?Module:{},moduleOverrides={},key;for(key in Module)Module.hasOwnProperty(key)&&(moduleOverrides[key]=Module[key]);var arguments_=[],thisProgram="./this.program",quit_=function(a,b){throw b;},ENVIRONMENT_IS_WEB=!1,ENVIRONMENT_IS_WORKER=!1,ENVIRONMENT_IS_NODE=!1,ENVIRONMENT_IS_SHELL=!1;ENVIRONMENT_IS_WEB="object"===typeof window;ENVIRONMENT_IS_WORKER="function"===typeof importScripts;
ENVIRONMENT_IS_NODE="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(a){return Module.locateFile?Module.locateFile(a,scriptDirectory):scriptDirectory+a}var read_,readAsync,readBinary,setWindowTitle,nodeFS,nodePath;
if(ENVIRONMENT_IS_NODE)scriptDirectory=ENVIRONMENT_IS_WORKER?require("path").dirname(scriptDirectory)+"/":__dirname+"/",read_=function(a,b){nodeFS||(nodeFS=require("fs"));nodePath||(nodePath=require("path"));a=nodePath.normalize(a);return nodeFS.readFileSync(a,b?null:"utf8")},readBinary=function(a){a=read_(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(thisProgram=process.argv[1].replace(/\\/g,"/")),arguments_=process.argv.slice(2),"undefined"!==typeof module&&
(module.exports=Module),process.on("uncaughtException",function(a){if(!(a instanceof ExitStatus))throw a;}),process.on("unhandledRejection",abort),quit_=function(a){process.exit(a)},Module.inspect=function(){return"[Emscripten Module object]"};else if(ENVIRONMENT_IS_SHELL)"undefined"!=typeof read&&(read_=function(a){return read(a)}),readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?
arguments_=scriptArgs:"undefined"!=typeof arguments&&(arguments_=arguments),"function"===typeof quit&&(quit_=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ENVIRONMENT_IS_WEB||ENVIRONMENT_IS_WORKER)ENVIRONMENT_IS_WORKER?scriptDirectory=self.location.href:document.currentScript&&(scriptDirectory=document.currentScript.src),scriptDirectory=0!==scriptDirectory.indexOf("blob:")?
scriptDirectory.substr(0,scriptDirectory.lastIndexOf("/")+1):"",read_=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ENVIRONMENT_IS_WORKER&&(readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):
c()};d.onerror=c;d.send(null)},setWindowTitle=function(a){document.title=a};var out=Module.print||console.log.bind(console),err=Module.printErr||console.warn.bind(console);for(key in moduleOverrides)moduleOverrides.hasOwnProperty(key)&&(Module[key]=moduleOverrides[key]);moduleOverrides=null;Module.arguments&&(arguments_=Module.arguments);Module.thisProgram&&(thisProgram=Module.thisProgram);Module.quit&&(quit_=Module.quit);var wasmBinary;Module.wasmBinary&&(wasmBinary=Module.wasmBinary);var noExitRuntime;
Module.noExitRuntime&&(noExitRuntime=Module.noExitRuntime);"object"!==typeof WebAssembly&&abort("no native wasm support detected");var wasmMemory,wasmTable=new WebAssembly.Table({initial:211,maximum:211,element:"anyfunc"}),ABORT=!1,EXITSTATUS=0;function assert(a,b){a||abort("Assertion failed: "+b)}function getCFunc(a){var b=Module["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function ccall(a,b,c,d,f){f={string:function(l){var q=0;if(null!==l&&void 0!==l&&0!==l){var t=(l.length<<2)+1;q=stackAlloc(t);stringToUTF8(l,q,t)}return q},array:function(l){var q=stackAlloc(l.length);writeArrayToMemory(l,q);return q}};var k=getCFunc(a),g=[];a=0;if(d)for(var h=0;h<d.length;h++){var m=f[c[h]];m?(0===a&&(a=stackSave()),g[h]=m(d[h])):g[h]=d[h]}c=k.apply(null,g);c=function(l){return"string"===b?UTF8ToString(l):"boolean"===b?!!l:l}(c);0!==a&&stackRestore(a);return c}
var UTF8Decoder="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function UTF8ArrayToString(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&UTF8Decoder)return UTF8Decoder.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|k);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|g:(f&7)<<18|k<<12|g<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function UTF8ToString(a,b){return a?UTF8ArrayToString(HEAPU8,a,b):""}
function stringToUTF8Array(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var k=0;k<a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var h=a.charCodeAt(++k);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function stringToUTF8(a,b,c){return stringToUTF8Array(a,HEAPU8,b,c)}function lengthBytesUTF8(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function allocateUTF8(a){var b=lengthBytesUTF8(a)+1,c=_malloc(b);c&&stringToUTF8Array(a,HEAP8,c,b);return c}function writeArrayToMemory(a,b){HEAP8.set(a,b)}var WASM_PAGE_SIZE=65536;function alignUp(a,b){0<a%b&&(a+=b-a%b);return a}
var buffer,HEAP8,HEAPU8,HEAP16,HEAPU16,HEAP32,HEAPU32,HEAPF32,HEAPF64;function updateGlobalBufferAndViews(a){buffer=a;Module.HEAP8=HEAP8=new Int8Array(a);Module.HEAP16=HEAP16=new Int16Array(a);Module.HEAP32=HEAP32=new Int32Array(a);Module.HEAPU8=HEAPU8=new Uint8Array(a);Module.HEAPU16=HEAPU16=new Uint16Array(a);Module.HEAPU32=HEAPU32=new Uint32Array(a);Module.HEAPF32=HEAPF32=new Float32Array(a);Module.HEAPF64=HEAPF64=new Float64Array(a)}
var DYNAMIC_BASE=5252704,DYNAMICTOP_PTR=9664,INITIAL_INITIAL_MEMORY=Module.INITIAL_MEMORY||16777216;if(wasmMemory=Module.wasmMemory?Module.wasmMemory:new WebAssembly.Memory({initial:INITIAL_INITIAL_MEMORY/WASM_PAGE_SIZE,maximum:2147483648/WASM_PAGE_SIZE}))buffer=wasmMemory.buffer;INITIAL_INITIAL_MEMORY=buffer.byteLength;updateGlobalBufferAndViews(buffer);HEAP32[DYNAMICTOP_PTR>>2]=DYNAMIC_BASE;
function callRuntimeCallbacks(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(Module);else{var c=b.func;"number"===typeof c?void 0===b.arg?Module.dynCall_v(c):Module.dynCall_vi(c,b.arg):c(void 0===b.arg?null:b.arg)}}}var __ATPRERUN__=[],__ATINIT__=[],__ATMAIN__=[],__ATPOSTRUN__=[],runtimeInitialized=!1,runtimeExited=!1;
function preRun(){if(Module.preRun)for("function"==typeof Module.preRun&&(Module.preRun=[Module.preRun]);Module.preRun.length;)addOnPreRun(Module.preRun.shift());callRuntimeCallbacks(__ATPRERUN__)}function initRuntime(){runtimeInitialized=!0;callRuntimeCallbacks(__ATINIT__)}function preMain(){callRuntimeCallbacks(__ATMAIN__)}function exitRuntime(){runtimeExited=!0}
function postRun(){if(Module.postRun)for("function"==typeof Module.postRun&&(Module.postRun=[Module.postRun]);Module.postRun.length;)addOnPostRun(Module.postRun.shift());callRuntimeCallbacks(__ATPOSTRUN__)}function addOnPreRun(a){__ATPRERUN__.unshift(a)}function addOnPostRun(a){__ATPOSTRUN__.unshift(a)}var runDependencies=0,runDependencyWatcher=null,dependenciesFulfilled=null;
function addRunDependency(a){runDependencies++;Module.monitorRunDependencies&&Module.monitorRunDependencies(runDependencies)}function removeRunDependency(a){runDependencies--;Module.monitorRunDependencies&&Module.monitorRunDependencies(runDependencies);0==runDependencies&&(null!==runDependencyWatcher&&(clearInterval(runDependencyWatcher),runDependencyWatcher=null),dependenciesFulfilled&&(a=dependenciesFulfilled,dependenciesFulfilled=null,a()))}Module.preloadedImages={};Module.preloadedAudios={};
function abort(a){if(Module.onAbort)Module.onAbort(a);a+="";err(a);ABORT=!0;EXITSTATUS=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function hasPrefix(a,b){return String.prototype.startsWith?a.startsWith(b):0===a.indexOf(b)}var dataURIPrefix="data:application/octet-stream;base64,";function isDataURI(a){return hasPrefix(a,dataURIPrefix)}var fileURIPrefix="file://";function isFileURI(a){return hasPrefix(a,fileURIPrefix)}var wasmBinaryFile="easyw.wasm";
isDataURI(wasmBinaryFile)||(wasmBinaryFile=locateFile(wasmBinaryFile));function getBinary(){try{if(wasmBinary)return new Uint8Array(wasmBinary);if(readBinary)return readBinary(wasmBinaryFile);throw"both async and sync fetching of the wasm failed";}catch(a){abort(a)}}
function getBinaryPromise(){return wasmBinary||!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER||"function"!==typeof fetch||isFileURI(wasmBinaryFile)?new Promise(function(a,b){a(getBinary())}):fetch(wasmBinaryFile,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+wasmBinaryFile+"'";return a.arrayBuffer()}).catch(function(){return getBinary()})}
function createWasm(){function a(f,k){Module.asm=f.exports;removeRunDependency("wasm-instantiate")}function b(f){a(f.instance)}function c(f){return getBinaryPromise().then(function(k){return WebAssembly.instantiate(k,d)}).then(f,function(k){err("failed to asynchronously prepare wasm: "+k);abort(k)})}var d={a:asmLibraryArg};addRunDependency("wasm-instantiate");if(Module.instantiateWasm)try{return Module.instantiateWasm(d,a)}catch(f){return err("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||isDataURI(wasmBinaryFile)||isFileURI(wasmBinaryFile)||"function"!==typeof fetch)return c(b);fetch(wasmBinaryFile,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(k){err("wasm streaming compile failed: "+k);err("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}}
var ASM_CONSTS={1745:function(){update()},1754:function(a){postMessage(["timer",a])},1784:function(a){postMessage(["init",a])},1814:function(a){postMessage(["ide","info",a])},1851:function(a){postMessage(["ide","selline",a])},1891:function(a){postMessage(["ide","output",UTF8ToString(a)])},1943:function(a){postMessage(["print",UTF8ToString(a)+"\n"])},1995:function(a){postMessage(["print",UTF8ToString(a)])},2040:function(a,b,c){push([9,a,b,c])},2065:function(a){push([6,UTF8ToString(a)])},2096:function(a,
b){push([1,a,b])},2117:function(a,b){push([2,a,b])},2138:function(a,b){push([4,a,b])},2159:function(a){push([3,a])},2176:function(a){push([8,a])},2193:function(a){push([7,a])},2210:function(a){push([10,a])},2228:function(a){push([11,a])},2246:function(){update();postMessage(["exit"])},2278:function(){list=[]},2288:function(a,b){list.push([a,b])},2312:function(){push([5,list])},2328:function(){push([12,list])},2345:function(){postMessage(["sound",list]);list=[]},2385:function(){step()},2392:function(){input()},
3396:function(){postMessage(["started"])},4125:function(){return lang.charCodeAt(0)+256*lang.charCodeAt(1)}};function _emscripten_asm_const_iii(a,b,c){b=readAsmConstArgs(b,c);return ASM_CONSTS[a].apply(null,b)}__ATINIT__.push({func:function(){___wasm_call_ctors()}});function _emscripten_memcpy_big(a,b,c){HEAPU8.copyWithin(a,b,b+c)}function _emscripten_random(){return Math.random()}function _emscripten_get_heap_size(){return HEAPU8.length}
function emscripten_realloc_buffer(a){try{return wasmMemory.grow(a-buffer.byteLength+65535>>>16),updateGlobalBufferAndViews(wasmMemory.buffer),1}catch(b){}}function _emscripten_resize_heap(a){a>>>=0;var b=_emscripten_get_heap_size();if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.min(2147483648,alignUp(Math.max(16777216,a,d),65536));if(emscripten_realloc_buffer(d))return!0}return!1}function _exit(a){exit(a)}
var PATH={splitPath:function(a){return/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1)},normalizeArray:function(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},normalize:function(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=PATH.normalizeArray(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+
a},dirname:function(a){var b=PATH.splitPath(a);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},basename:function(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},extname:function(a){return PATH.splitPath(a)[3]},join:function(){var a=Array.prototype.slice.call(arguments,0);return PATH.normalize(a.join("/"))},join2:function(a,b){return PATH.normalize(a+"/"+b)}},SYSCALLS={mappings:{},buffers:[null,[],[]],printChar:function(a,b){var c=SYSCALLS.buffers[a];
0===b||10===b?((1===a?out:err)(UTF8ArrayToString(c,0)),c.length=0):c.push(b)},varargs:void 0,get:function(){SYSCALLS.varargs+=4;return HEAP32[SYSCALLS.varargs-4>>2]},getStr:function(a){return UTF8ToString(a)},get64:function(a,b){return a}};function _fd_close(a){return 0}function _fd_seek(a,b,c,d,f){}function _fd_write(a,b,c,d){for(var f=0,k=0;k<c;k++){for(var g=HEAP32[b+8*k>>2],h=HEAP32[b+(8*k+4)>>2],m=0;m<h;m++)SYSCALLS.printChar(a,HEAPU8[g+m]);f+=h}HEAP32[d>>2]=f;return 0}
function _gettimeofday(a){var b=Date.now();HEAP32[a>>2]=b/1E3|0;HEAP32[a+4>>2]=b%1E3*1E3|0;return 0}var ___tm_current=9680,___tm_timezone=(stringToUTF8("GMT",9728,4),9728);
function _tzset(){function a(k){return(k=k.toTimeString().match(/\(([A-Za-z ]+)\)$/))?k[1]:"GMT"}if(!_tzset.called){_tzset.called=!0;HEAP32[__get_timezone()>>2]=60*(new Date).getTimezoneOffset();var b=(new Date).getFullYear(),c=new Date(b,0,1);b=new Date(b,6,1);HEAP32[__get_daylight()>>2]=Number(c.getTimezoneOffset()!=b.getTimezoneOffset());var d=a(c),f=a(b);d=allocateUTF8(d);f=allocateUTF8(f);b.getTimezoneOffset()<c.getTimezoneOffset()?(HEAP32[__get_tzname()>>2]=d,HEAP32[__get_tzname()+4>>2]=f):
(HEAP32[__get_tzname()>>2]=f,HEAP32[__get_tzname()+4>>2]=d)}}
function _localtime_r(a,b){_tzset();a=new Date(1E3*HEAP32[a>>2]);HEAP32[b>>2]=a.getSeconds();HEAP32[b+4>>2]=a.getMinutes();HEAP32[b+8>>2]=a.getHours();HEAP32[b+12>>2]=a.getDate();HEAP32[b+16>>2]=a.getMonth();HEAP32[b+20>>2]=a.getFullYear()-1900;HEAP32[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;HEAP32[b+28>>2]=d;HEAP32[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==
Math.min(c,d))|0;HEAP32[b+32>>2]=a;a=HEAP32[__get_tzname()+(a?4:0)>>2];HEAP32[b+40>>2]=a;return b}function _localtime(a){return _localtime_r(a,___tm_current)}var _emscripten_get_now;_emscripten_get_now=ENVIRONMENT_IS_NODE?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?dateNow:function(){return performance.now()};function _usleep(a){for(var b=_emscripten_get_now();_emscripten_get_now()-b<a/1E3;);}Module._usleep=_usleep;
function setErrNo(a){return HEAP32[___errno_location()>>2]=a}function _nanosleep(a,b){if(0===a)return setErrNo(28),-1;var c=HEAP32[a>>2];a=HEAP32[a+4>>2];if(0>a||999999999<a||0>c)return setErrNo(28),-1;0!==b&&(HEAP32[b>>2]=0,HEAP32[b+4>>2]=0);return _usleep(1E6*c+a/1E3)}function __isLeapYear(a){return 0===a%4&&(0!==a%100||0===a%400)}function __arraySum(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var __MONTH_DAYS_LEAP=[31,29,31,30,31,30,31,31,30,31,30,31],__MONTH_DAYS_REGULAR=[31,28,31,30,31,30,31,31,30,31,30,31];function __addDays(a,b){for(a=new Date(a.getTime());0<b;){var c=__isLeapYear(a.getFullYear()),d=a.getMonth();c=(c?__MONTH_DAYS_LEAP:__MONTH_DAYS_REGULAR)[d];if(b>c-a.getDate())b-=c-a.getDate()+1,a.setDate(1),11>d?a.setMonth(d+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function _strftime(a,b,c,d){function f(e,n,p){for(e="number"===typeof e?e.toString():e||"";e.length<n;)e=p[0]+e;return e}function k(e,n){return f(e,n,"0")}function g(e,n){function p(v){return 0>v?-1:0<v?1:0}var u;0===(u=p(e.getFullYear()-n.getFullYear()))&&0===(u=p(e.getMonth()-n.getMonth()))&&(u=p(e.getDate()-n.getDate()));return u}function h(e){switch(e.getDay()){case 0:return new Date(e.getFullYear()-1,11,29);case 1:return e;case 2:return new Date(e.getFullYear(),0,3);case 3:return new Date(e.getFullYear(),
0,2);case 4:return new Date(e.getFullYear(),0,1);case 5:return new Date(e.getFullYear()-1,11,31);case 6:return new Date(e.getFullYear()-1,11,30)}}function m(e){e=__addDays(new Date(e.tm_year+1900,0,1),e.tm_yday);var n=new Date(e.getFullYear(),0,4),p=new Date(e.getFullYear()+1,0,4);n=h(n);p=h(p);return 0>=g(n,e)?0>=g(p,e)?e.getFullYear()+1:e.getFullYear():e.getFullYear()-1}var l=HEAP32[d+40>>2];d={tm_sec:HEAP32[d>>2],tm_min:HEAP32[d+4>>2],tm_hour:HEAP32[d+8>>2],tm_mday:HEAP32[d+12>>2],tm_mon:HEAP32[d+
16>>2],tm_year:HEAP32[d+20>>2],tm_wday:HEAP32[d+24>>2],tm_yday:HEAP32[d+28>>2],tm_isdst:HEAP32[d+32>>2],tm_gmtoff:HEAP32[d+36>>2],tm_zone:l?UTF8ToString(l):""};c=UTF8ToString(c);l={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U",
"%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in l)c=c.replace(new RegExp(q,"g"),l[q]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),r="January February March April May June July August September October November December".split(" ");l={"%a":function(e){return t[e.tm_wday].substring(0,3)},"%A":function(e){return t[e.tm_wday]},"%b":function(e){return r[e.tm_mon].substring(0,3)},"%B":function(e){return r[e.tm_mon]},"%C":function(e){return k((e.tm_year+1900)/100|
0,2)},"%d":function(e){return k(e.tm_mday,2)},"%e":function(e){return f(e.tm_mday,2," ")},"%g":function(e){return m(e).toString().substring(2)},"%G":function(e){return m(e)},"%H":function(e){return k(e.tm_hour,2)},"%I":function(e){e=e.tm_hour;0==e?e=12:12<e&&(e-=12);return k(e,2)},"%j":function(e){return k(e.tm_mday+__arraySum(__isLeapYear(e.tm_year+1900)?__MONTH_DAYS_LEAP:__MONTH_DAYS_REGULAR,e.tm_mon-1),3)},"%m":function(e){return k(e.tm_mon+1,2)},"%M":function(e){return k(e.tm_min,2)},"%n":function(){return"\n"},
"%p":function(e){return 0<=e.tm_hour&&12>e.tm_hour?"AM":"PM"},"%S":function(e){return k(e.tm_sec,2)},"%t":function(){return"\t"},"%u":function(e){return e.tm_wday||7},"%U":function(e){var n=new Date(e.tm_year+1900,0,1),p=0===n.getDay()?n:__addDays(n,7-n.getDay());e=new Date(e.tm_year+1900,e.tm_mon,e.tm_mday);return 0>g(p,e)?(n=__arraySum(__isLeapYear(e.getFullYear())?__MONTH_DAYS_LEAP:__MONTH_DAYS_REGULAR,e.getMonth()-1)-31,p=31-p.getDate()+n+e.getDate(),k(Math.ceil(p/7),2)):0===g(p,n)?"01":"00"},
"%V":function(e){var n=new Date(e.tm_year+1901,0,4),p=h(new Date(e.tm_year+1900,0,4));n=h(n);var u=__addDays(new Date(e.tm_year+1900,0,1),e.tm_yday);if(0>g(u,p))return"53";if(0>=g(n,u))return"01";e=p.getFullYear()<e.tm_year+1900?e.tm_yday+32-p.getDate():e.tm_yday+1-p.getDate();return k(Math.ceil(e/7),2)},"%w":function(e){return e.tm_wday},"%W":function(e){var n=new Date(e.tm_year,0,1),p=1===n.getDay()?n:__addDays(n,0===n.getDay()?1:7-n.getDay()+1);e=new Date(e.tm_year+1900,e.tm_mon,e.tm_mday);return 0>
g(p,e)?(n=__arraySum(__isLeapYear(e.getFullYear())?__MONTH_DAYS_LEAP:__MONTH_DAYS_REGULAR,e.getMonth()-1)-31,p=31-p.getDate()+n+e.getDate(),k(Math.ceil(p/7),2)):0===g(p,n)?"01":"00"},"%y":function(e){return(e.tm_year+1900).toString().substring(2)},"%Y":function(e){return e.tm_year+1900},"%z":function(e){e=e.tm_gmtoff;var n=0<=e;e=Math.abs(e)/60;return(n?"+":"-")+String("0000"+(e/60*100+e%60)).slice(-4)},"%Z":function(e){return e.tm_zone},"%%":function(){return"%"}};for(q in l)0<=c.indexOf(q)&&(c=
c.replace(new RegExp(q,"g"),l[q](d)));q=intArrayFromString(c,!1);if(q.length>b)return 0;writeArrayToMemory(q,a);return q.length-1}function _time(a){var b=Date.now()/1E3|0;a&&(HEAP32[a>>2]=b);return b}var readAsmConstArgsArray=[];function readAsmConstArgs(a,b){readAsmConstArgsArray.length=0;var c;for(b>>=2;c=HEAPU8[a++];)(c=105>c)&&b&1&&b++,readAsmConstArgsArray.push(c?HEAPF64[b++>>1]:HEAP32[b]),++b;return readAsmConstArgsArray}
function intArrayFromString(a,b,c){c=0<c?c:lengthBytesUTF8(a)+1;c=Array(c);a=stringToUTF8Array(a,c,0,c.length);b&&(c.length=a);return c}
var asmLibraryArg={a:_emscripten_asm_const_iii,m:_emscripten_memcpy_big,f:_emscripten_random,n:_emscripten_resize_heap,b:_exit,g:_fd_close,l:_fd_seek,d:_fd_write,e:_gettimeofday,j:_localtime,memory:wasmMemory,h:_nanosleep,i:_strftime,table:wasmTable,k:_time,c:_usleep},asm=createWasm(),___wasm_call_ctors=Module.___wasm_call_ctors=function(){return(___wasm_call_ctors=Module.___wasm_call_ctors=Module.asm.o).apply(null,arguments)},_errstr=Module._errstr=function(){return(_errstr=Module._errstr=Module.asm.p).apply(null,
arguments)},_malloc=Module._malloc=function(){return(_malloc=Module._malloc=Module.asm.q).apply(null,arguments)},_evt_func=Module._evt_func=function(){return(_evt_func=Module._evt_func=Module.asm.r).apply(null,arguments)},_evt_mouse=Module._evt_mouse=function(){return(_evt_mouse=Module._evt_mouse=Module.asm.s).apply(null,arguments)},_parse=Module._parse=function(){return(_parse=Module._parse=Module.asm.t).apply(null,arguments)},_format=Module._format=function(){return(_format=Module._format=Module.asm.u).apply(null,
arguments)},_caret=Module._caret=function(){return(_caret=Module._caret=Module.asm.v).apply(null,arguments)},_k_free=Module._k_free=function(){return(_k_free=Module._k_free=Module.asm.w).apply(null,arguments)},_exec=Module._exec=function(){return(_exec=Module._exec=Module.asm.x).apply(null,arguments)},_main=Module._main=function(){return(_main=Module._main=Module.asm.y).apply(null,arguments)},___errno_location=Module.___errno_location=function(){return(___errno_location=Module.___errno_location=Module.asm.z).apply(null,
arguments)},__get_tzname=Module.__get_tzname=function(){return(__get_tzname=Module.__get_tzname=Module.asm.A).apply(null,arguments)},__get_daylight=Module.__get_daylight=function(){return(__get_daylight=Module.__get_daylight=Module.asm.B).apply(null,arguments)},__get_timezone=Module.__get_timezone=function(){return(__get_timezone=Module.__get_timezone=Module.asm.C).apply(null,arguments)},stackSave=Module.stackSave=function(){return(stackSave=Module.stackSave=Module.asm.D).apply(null,arguments)},stackRestore=
Module.stackRestore=function(){return(stackRestore=Module.stackRestore=Module.asm.E).apply(null,arguments)},stackAlloc=Module.stackAlloc=function(){return(stackAlloc=Module.stackAlloc=Module.asm.F).apply(null,arguments)},dynCall_vi=Module.dynCall_vi=function(){return(dynCall_vi=Module.dynCall_vi=Module.asm.G).apply(null,arguments)},dynCall_v=Module.dynCall_v=function(){return(dynCall_v=Module.dynCall_v=Module.asm.H).apply(null,arguments)};Module.ccall=ccall;var calledRun;
function ExitStatus(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}var calledMain=!1;dependenciesFulfilled=function runCaller(){calledRun||run();calledRun||(dependenciesFulfilled=runCaller)};function callMain(a){a=Module._main;try{var b=a(0,0);exit(b,!0)}catch(c){c instanceof ExitStatus||("unwind"==c?noExitRuntime=!0:((b=c)&&"object"===typeof c&&c.stack&&(b=[c,c.stack]),err("exception thrown: "+b),quit_(1,c)))}finally{calledMain=!0}}
function run(a){function b(){if(!calledRun&&(calledRun=!0,Module.calledRun=!0,!ABORT)){initRuntime();preMain();if(Module.onRuntimeInitialized)Module.onRuntimeInitialized();shouldRunNow&&callMain(a);postRun()}}a=a||arguments_;0<runDependencies||(preRun(),0<runDependencies||(Module.setStatus?(Module.setStatus("Running..."),setTimeout(function(){setTimeout(function(){Module.setStatus("")},1);b()},1)):b()))}Module.run=run;
function exit(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime&&(ABORT=!0,EXITSTATUS=a,exitRuntime(),Module.onExit))Module.onExit(a);quit_(a,new ExitStatus(a))}}if(Module.preInit)for("function"==typeof Module.preInit&&(Module.preInit=[Module.preInit]);0<Module.preInit.length;)Module.preInit.pop()();var shouldRunNow=!0;Module.noInitialRun&&(shouldRunNow=!1);noExitRuntime=!0;run();function update(){0<cmds.length&&(postMessage(["list",cmds]),cmds=[])}
function push(a){cmds.push(a);1E4<cmds.length&&update()}
onmessage=function(a){a=a.data;var b=a[0];if("mouse"==b)Module.ccall("evt_mouse","null",["int","float","float"],[a[1],a[2],a[3]]),update();else if("animate"==b)Module.ccall("evt_func","null",["int","string"],[1,null]),update();else if("timer"==b)Module.ccall("evt_func","null",["int","string"],[2,null]),update();else if("key"==b)Module.ccall("evt_func","null",["int","string"],[0,a[1]]),update();else if("stop_ping"==b)Module.ccall("k_free","null",null,null),postMessage(["stop_pong"]);else if("init"==
b)sab=a[1],lang=a[2];else if("run"==b){b=Module.ccall("parse","int",["string","int","int"],[a[1],a[2],a[3]]);var c=Module.ccall("format","string",null,null),d=Module.ccall("caret","int",null,null);0<=b?(a=Module.ccall("errstr","string",null,null),postMessage(["ide","src_err",c,b,d,a])):(postMessage(["ide","src",c,b,d]),cmds=[],a=Module.ccall("exec",null,["int","string"],[a[2],a[4]]),update(),0==a&&postMessage(["done"]))}else"runx"==b?(b=Module.ccall("parse","int",["string","int","int"],[a[1],a[2],
a[3]]),0<=b?postMessage(["error"]):(cmds=[],a=Module.ccall("exec",null,["int","string"],[a[2],a[4]]),update(),0==a&&postMessage(["done"]))):"format"==b?(b=Module.ccall("parse","int",["string","int","int"],[a[1],14,0]),c=Module.ccall("format","string",null,null),d=Module.ccall("caret","int",null,null),a=Module.ccall("errstr","string",null,null),postMessage(["ide","src_nl",c,b,d,a])):"formatID"==b?(Module.ccall("parse","int",["string","int","int"],[a[1],6,0]),c=Module.ccall("format","string",null,null),
postMessage(["ide","src2",c,a[2]])):"error"==b&&(a=Module.ccall("error","string",null,null),postMessage(["ide","error",a]))};
function input(){if(null==sab){var a="ERROR: 'input' does not work, because 'SharedArrayBuffer' is disabled in your browser\n";console.log(a);postMessage(["ide","print",a])}else update(),postMessage(["ide","input"]),a=new Int32Array(sab),Atomics.wait(a,1,0),Atomics.store(a,1,0),a=new Uint16Array(sab),0!=a[4]?(a=String.fromCharCode.apply(null,a.slice(5,a[4]+4)),Module.ccall("evt_func","null",["int","string"],[3,a])):Module.ccall("evt_func","null",["int","string"],[4,""])}
function step(){update();postMessage(["ide","step"]);var a=new Int32Array(sab);Atomics.wait(a,0,0);Atomics.store(a,0,0);Module.ccall("evt_func","null",["int"],[5+a[2]])};
